FROM nginx:1.29-alpine3.22
COPY /docker/config/etc/nginx/nginx.conf /etc/nginx/nginx.conf
COPY /docker/config/etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY /docker/config/etc/nginx/conf.d/timeout.conf /etc/nginx/conf.d/timeout.conf
